runtime: nodejs12

instance_class: F2

handlers:
  - url: /favicon\.ico
    static_files: static/favicon.ico
    upload: static/favicon\.ico

  - url: /sw.js
    static_files: static/sw.js
    upload: static/sw.js

  - url: /sitemap.xml
    static_files: static/sitemap.xml
    upload: static/sitemap\.xml

  - url: /static
    static_dir: public

  - url: /assets
    static_dir: assets

  - url: /_nuxt
    static_dir: .nuxt/dist/client
    secure: always

  - url: /(.*\.(gif|png|jpg|ico|txt))$
    static_files: static/\1
    upload: static/.*\.(gif|png|jpg|ico|txt)$
    secure: always

  - url: /.*
    script: auto
    secure: always

env_variables:
  HOST: '0.0.0.0'
  PORT: '8080'

automatic_scaling:
  min_idle_instances: automatic         # idle状態にあるインスタンスの最小値
  max_idle_instances: 1                 # idle状態にあるインスタンスの最大値
  min_pending_latency: 3000ms  # リクエストを処理するまでに許される待ち時間の最小
  max_pending_latency: automatic
